language: android
script: 
    - ./gradlew build check

android:
  components:
    - build-tools-23.0.1
    - android-23
    - platform-tools
    - extra-android-m2repository
    - extra-android-support

sudo: false
